# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '05_DHSpringDemo' do

  use_frameworks!

  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'

end
