# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '08_DHNetworkingDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 08_DHNetworkingDemo
  pod 'Moya/RxSwift'
  pod 'SwiftyJSON'
  pod 'HandyJSON', '~> 4.0.0-beta.1'
  pod 'Kingfisher', '~> 4.5.0'
end
