# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DHAlamofireDemo' do
  use_frameworks!

  pod 'Alamofire', '~> 4.4'
  pod 'ObjectMapper', '~> 2.2'
  pod 'SwiftyJSON'
end
