# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FDFullscreenPopGestureDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FDFullscreenPopGestureDemo
  pod 'FDFullscreenPopGesture', '1.1'

  target 'FDFullscreenPopGestureDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FDFullscreenPopGestureDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
